# Take-Home Assignment 2



## Part 1 - Numpy

### Question 1
Define two custom numpy arrays, A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [3]:

import numpy as np

# Define two custom numpy arrays A and B
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([4, 5, 6, 7, 8, 9])

# Stack A and B vertically and horizontally
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)


Vertical Stack:
 [[1 2 3 4 5 6]
 [4 5 6 7 8 9]]
Horizontal Stack:
 [1 2 3 4 5 6 4 5 6 7 8 9]


### Question 2
Find common elements between A and B using the intersection of two sets.

In [4]:

# Find common elements between A and B
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)


Common Elements: [4 5 6]


### Question 3
Extract all numbers from A which are within a specific range (e.g., between 5 and 10).

In [5]:

# Extract numbers from A within a specific range (5 to 10)
filtered_A = A[(A >= 5) & (A <= 10)]
print("Numbers in Range 5-10:", filtered_A)


Numbers in Range 5-10: [5 6]


### Question 4
Filter the rows of `iris_2d` where petal length (3rd column) > 1.5 and sepal length (1st column) < 5.0.

In [6]:

# Load dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Filter rows
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Rows:\n", filtered_iris)


Filtered Rows:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


## Part 2 - Pandas

### Question 1
From `df`, filter the 'Manufacturer', 'Model', and 'Type' for every 20th row starting from row 0.

In [7]:

import pandas as pd

# Load dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Filter required columns every 20th row
filtered_df = df.loc[::20, ['Manufacturer', 'Model', 'Type']]
print(filtered_df)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


/var/folders/73/4l1hsjs571387y9wktwsjsz00000gn/T/ipykernel_19618/358406178.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


### Question 2
Replace missing values in 'Min.Price' and 'Max.Price' columns with their respective mean.

In [8]:

# Replace missing values with mean
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)

# Display updated data
print(df[['Min.Price', 'Max.Price']].head())


   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


/var/folders/73/4l1hsjs571387y9wktwsjsz00000gn/T/ipykernel_19618/294109284.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
/var/folders/73/4l1hsjs571387y9wktwsjsz00000gn/T/ipykernel_19618/294109284.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting v

### Question 3
How to get the rows of a DataFrame where the row sum is greater than 100?

In [9]:

# Create a random DataFrame
random_df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Get rows where row sum > 100
row_sum_filtered = random_df[random_df.sum(axis=1) > 100]

print("Rows where sum > 100:\n", row_sum_filtered)


Rows where sum > 100:
      0   1   2   3
5   17  34  39  39
6   35  29  30  12
8   37  19  21  35
12  30  28  20  28
